### ISSUE TITLE
Knotenliste auf VPN5 nicht erreichbar

### ISSUE THREAD

**Issue by 205er** [ffbsee/firmware#10]
Moin,

im server repository kann man leider keine Issues melden, deswegen hier:

- https://vpn5.ffbsee.de/list.html führt ins "Leere (Error 404)

**Comment by mart-ffbsee** [comment]
fixed

**Comment by mart-ffbsee** [comment]
btw. der hostname ist gar nicht vpn5. Richtig ist https://speedtest5.ffbsee.de
