### ISSUE TITLE
Wunsch: Router-Neustart konfigurierbar

### ISSUE THREAD

**Issue by MH301** [ffbsee/firmware#13]
Es wäre praktisch, wenn es auf der Web-Oberfläche der Router eine Möglichkeit gäbe, den regelmäßigen Neustart eines Routers abzuschalten oder die Häufigkeit und die Uhrzeit einzustellen.

Richtig spannend wäre so etwas wie die Crontab UI https://github.com/alseambusher/crontab-ui
Damit könnte man z.B. nachts die WLAN Sendeleistung reduzieren. Ideen gibt es sicher viele...

Auch gut, wenn man genau weiß, was man tut:
https://blog.doenselmann.com/zeitgesteuertes-wlan-auf-openwrt-router/

**Comment by L3Dokt0r** [comment]
Der regelmäßige Router-Neustart wird in der Datei [/etc/crontab/root](https://github.com/ffbsee/firmware/blob/master/files/etc/crontabs/root) gesteuert. Und eigendlich will ich in dieser Datei nicht über irgendwelche Scripte rumpfuschen bzw. diese anpassen.

Die Idee des automatischen Neustarts ist, dass falls sich der Router mal aufgehangen haben sollte oder er mit einem Supernode verbunden ist der nicht mehr richtig funktioniert dann startet er nach ein paar Tagen neu und er funktioniert wieder! Und besser, der Router ist einmal alle 5 Tage ein paar Minuten weg, als dass er Monatelang nicht mehr funktioniert.

**Comment by DO1JLR** [comment]
wontfix
