### ISSUE TITLE
In der Knotenliste werden offline-Knoten mit Clients aufgeführt.

### ISSUE THREAD

**Issue by 205er** [ffbsee/firmware#22]
In der Knotenliste werden Knoten, die als "offline" gekennzeichnet sind, mit verbundenen Clients aufgeführt. Ist das so gewollt und ich erkenne den Sinn dahinter nur noch nicht, oder ist das ein Bug?

**Comment by L3Dokt0r** [comment]
Ich würde vermuten, dass das ein Bug beim Meshviewer ist!

**Comment by L3Dokt0r** [comment]
https://github.com/ffbsee/meshviewer

**Comment by DO1JLR** [comment]
any updates?
