### ISSUE TITLE
Uhrzeit meshender Nodes stimmt nicht

### ISSUE THREAD

**Issue by 205er** [ffbsee/firmware#24]
Die Uhrzeit von Nodes, die über keine eigene Internetverbindung verfügen, also nur über das Mesh-Netz angebunden sind, stimmt nicht.

**Comment by L3Dokt0r** [comment]
Lösung: Einen ntp Server der auch im Freifunk via IPv6 erreichbar ist!

**Comment by 205er** [comment]
Stellst du einen bereit? ;-)

**Comment by L3Dokt0r** [comment]
demnächst...

**Comment by 205er** [comment]
OK, Teamarbeit:
Du kümmerst dich um den VPN-Service und ich passe die Router-Config an und teste das Ganze!?
Hoffe das motiviert dich ein wenig :-)

**Comment by L3Dokt0r** [comment]
```bash
ntpdate -q ntp.ffbsee
```

**Comment by 205er** [comment]
Mit Release 0.7.0 behoben
