### ISSUE TITLE
Nodeliste: Link auf "Karte" führt ins Leere

### ISSUE THREAD

**Issue by 205er** [ffbsee/firmware#25]
In der [Nodesliste](https://vpn1.ffbsee.de/list.html) wird im Menü auf eine "Karte" verlinkt (https://vpn1.ffbsee.de/geomap.html). Diese Kartenansicht funktioniert jedoch nicht (mehr).

Vorschlag: auf Meshviewer verlinken.

**Comment by L3Dokt0r** [comment]
Gegenvorschlag: Die Verwendung einer moderneren Liste, die auf den Daten des Meshviewers basiert!

**Comment by L3Dokt0r** [comment]
erledigt
