### ISSUE TITLE
files/www/lan/cgi-bin/home

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/firmware#37]
files/www/lan/cgi-bin/home nochmal genau anschauen und Säubern!

**Comment by L3Dokt0r** [comment]
https://github.com/freifunk-bielefeld/firmware/commit/5f7722e008cd1370c70dd07dd77439710b036bb8

https://github.com/freifunk-bielefeld/firmware/commit/ba7f08765edba0e2e6dfe2a0b5a8aeaf1df37e24
