### ISSUE TITLE
Kompilieren schlägt fehl (0001-alfred-adjust-intervals.patch)

### ISSUE THREAD

**Issue by daver360** [ffbsee/firmware#38]
Make gefällt diese Datei hier nicht:
./source/feeds/routing/alfred/patches/0001-alfred-adjust-intervals.patch
Verbose Output
`Applying ./patches/0001-alfred-adjust-intervals.patch using plaintext: `
`patching file alfred.h`
`Hunk #1 FAILED at 34.`
`1 out of 1 hunk FAILED -- saving rejects to file alfred.h.rej`

Ich hab die Datei gelöscht und danach ging es. (Offensichtlich nicht die richtige Lösung der Problems) ;)

**Comment by DO1JLR** [comment]
Und genau deswegen ist es ein Deelopement Branch!

**Comment by daver360** [comment]
Und wie genau hilft dieser Kommentar jetzt beim lösen des Problems? :D

**Comment by mart-ffbsee** [comment]
fixed with commit 80a92cd34d36e57a00cc033207f0b3eb6b825ae4
