### ISSUE TITLE
D-Link DIR-615 H1/2 Support

### ISSUE THREAD

**Issue by HACKER-3000** [ffbsee/firmware#48]
War ja schon mal da also...
Ich hab echt kein bock alte fw(nur wifi g statt n) zu verwenden!

Bitte als precompiled bereitstellen!

**Comment by DO1JLR** [comment]
Hallo @HACKER-3000 

Deinem Nicknamen zufolge schaffst du das auch selber.
Wo scheitest du dennbeim compilieren?

L3D

*PS: Freundlicher formulieren bringt oft freundlichere Hilfe. Just saying.*

**Comment by DO1JLR** [comment]
@HACKER-3000 Irgendwelche Fortschritte?

**Comment by HACKER-3000** [comment]
Habe gerade die archieve durchstöbert, und die 1.0.5 vesion, welche die aktuelle stable ist unterstützt ihn!
Da ist ein precompiled, das aber leider wie viele andere nicht auf dem fw wizard ist...

**Comment by HACKER-3000** [comment]
Problem is halt das der wifi treiber nur g kann...
WHY?
Ist das ein owrt problem, obwohl da n unterstützt wird...

**Comment by DO1JLR** [comment]
> Habe gerade die archieve durchstöbert, und die 1.0.5 vesion, welche die aktuelle stable ist unterstützt ihn!
> Da ist ein precompiled, das aber leider wie viele andere nicht auf dem fw wizard ist...

Für die firmware-wizzard problematik wende dich bitte direkt an das passende Repo. Am besten mit Pull-Request:
https://github.com/ffbsee/firmware-selector.git

Ich bin mit dem Firmware-Wizard auch nicht ganz glücklich, aber @205er und @mart-ffbsee finden ihn eben echt cool und da will ich niemanden aufhalten!

**Comment by DO1JLR** [comment]
> Problem is halt das der wifi treiber nur g kann...
> WHY?
> Ist das ein owrt problem, obwohl da n unterstützt wird...

Es ist nicht leicht für abgekündigte Hardware noch support zu leisten.
Erst recht nicht, wenn man selber nicht im Besitz dieser Hardware ist.

Um das Problem mit der fehlenden 8021n unterstützung weiter einzugrenzen...
  + Hast du mal versucht eine original OpenWRT Firmware zu installieren?
    - Möglicherweise hat die ja die gewünschten Features
    - Installiere dir die Weboberfläche (luci) und versuche es darüber zu aktivieren
    - Schaue dir die netzwerk- und WLAN Configurationsdateien an und vergleiche Sie mit denen von Freifunk Bodensee
       * Fallen dir Unterschiede auf?
        * Wenn du die für 8021n wichtigen teile der config übernimmst, funktioniert es dann?
    - Hast du dein Problem mal versucht zu ergoogeln?
    - Im Freifunk Forum gibt es auch oft nützliche Hinweise zu solchen Themen
  + Hast du das mal mit anderer Firmware ausprobiert?
    - Wenn es mit der Ulmer firmware funktioniert. wäre das spannend zu wissen. Denn Bodensee und Ulm ist (Firmwaremäßig) nahezu identisch.
    - FF3L und FFS ist auch nett... Die anderen bestimmt auch, mit denen habe ich aber weniger Kontakt.
  + Hast du mal probiert die Firmware selber zu bauen?
    - In diesem Prozess lassen sich auch viele Module aktivieren oder deaktivieren... Eventuell sind die standardeinstellung noch optimierungswürdig?
