### ISSUE TITLE
CPE210 resetbutton is not doing anything

### ISSUE THREAD

**Issue by phschoen** [ffbsee/firmware#51]
The Reset button on a CP210 does not have any functionality.
I locked my self out from the webui and tried to reset which had no effect. 

the only solution was to open it and solder to the rs232 and open the connection manually.

**Comment by DO1JLR** [comment]
Dann geb doch noch ein paar mehr Infos Preis:

 + welche Firmwareversion hattest du verwendet?
 + wie hast du auf den Router versucht zuzugreifen?
   * hast du dir eine feste ip gesetzt?
   * hatte ping funktioniert?
   * ssh oder telnet?
   * was sagte den ein ipv6 ping ``ping ff02::1%interfacename``
 + lässt sich das reproduzieren mit der original openwrt firmware?
 + welche Hardware Version ist dein CPE210 genau?
 + weitere Details?

**Comment by phschoen** [comment]
TP-Link CPE210 v1.0
Firmware Version: 1.0.5
LEDE Version: 17.01-SNAPSHOT
Batman-Adv Version: 2018.1
Fastd Version: v18

was funktionierte:
ping ja 
ssh nein telnet nein web nein

**Comment by DO1JLR** [comment]
Ok, wenn man reset hält wird da auch nichts resettet, sonsern man kann in den Recovery Modus booten...

[Google + OpenWRT + Recovery -> Erstes Ergebnis](https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset)

**Comment by phschoen** [comment]
Lilian danke für dein Capain Obvious Hinweis darauf bin ich auch gekommen sonst wäre ich schlecht in der Lage gewesen auf Anhieb die serial Pins des CPE zu finden. 

Jedoch ist er nicht zurückgefallen auf den Recovery Modus, da ich sonst via ssh drauf gekommen wäre und auch das wlan (Freifunk und mesh) nicht vorhanden gewesen wäre. Auch hätte ich dies über serial, dass er zurückfallen würde.

>  OpenWrt allows you to boot into a failsafe mode that overrides its current configuration [...]
>  Make sure you use a wired connection, since the failsafe will disable your wireless connectivity. 

Danke für deine "qualifizierte" Antwort. Ich schließe dieses issue, da ich den Fehler beheben konnte und keine Lust/Zeit auf das Niveau "i google that for you" habe und so es **nicht** nochmal ausprobieren werde.

**Comment by DO1JLR** [comment]
Alter!

**Comment by DO1JLR** [comment]
Bei der Menge an Idioten und der Beschreibung die sehr nach einem Anwenderfehler anhört ist es nicht leicht, zu sagen ob jemand wirklich alles richtig gemacht hat!

Gerade auch, weil das so an sich funktionieren sollte...

Toll das es für dich funktioniert hat. 

Schreib doch deinen Weg auf die Webseite, damit andere Menschen auch etwas davon haben könnten.

*Ach nein, das wäre ja aufwand...*

**Comment by phschoen** [comment]
ich glaube du wirfst den falschen das an den Kopf. Ich selbst habe nichts davon mir Router zu kaufen und für andere zu betreiben :) dennoch mach ich es und habe erst vor kurzem weitere bestellt. :+1: 
Im Übrigen fehlt auf dem Wiki generell ein Eintrag mit rs232. [Ach nein den hab ich ja geschrieben...](https://wiki.freifunk.net/TP-Link_CPE210#rs232).

einfach normal mit den Leuten reden ohne sie direkt für dumm zu verkaufen egal ob jemand Endanwender ist oder nicht und Software ist nie ohne Fehler. Daher erst mal nett sein und weiter fragen schließlich sind wir alle irgendwo Endanwender ;)
